# This workflow is run on repository initalisation and gets deleted when the template is used
name: Delay Repository Initialisation

on:
  push:
    branches:
      - main

jobs:
  sleep:
    name: Wait for terraform apply to complete setting up the repo
    if: ${{ github.event.repository.name != 'basic-template' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Sleep for 60 seconds
        shell: bash
        run: sleep 60s
